---

- hosts: all
  become: true
  tasks:
#  - name: Update repository index
#    apt:
#      update_cache: true
#    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install the apache and php
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
      state: latest
      update_cache: true
  