---

- hosts: all
  become: true
  tasks:
  - name: Update repository index
    apt:
      update_cache: true

  - name: remove the apache2 package
    apt:
      name: apache2
      state: absent
  
  - name: remove php support for apache2
    apt:
      name: libapache2-mod-php
      state: absent

