---

- hosts: all
  become: true
  pre_tasks:
  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  - name: install the apache and php
    tags: apache,apache2,ubuntu
    package:
      name: 
      - "{{ apache_package }}"
      - "{{ php_package }}"
      state: latest
  - name: copy default html file for site
    tags: apache,apached2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
- hosts: db_servers
  become: true
  tasks:
  - name: Install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
  
- hosts: file_servers
  become: true
  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
